name: 'Ghuzzle Action'
description: 'Runs the ghuzzle tool with specified config'
inputs:
  config:
    description: 'Path to the config file'
    required: false
    default: './ghuzzle.json'
  build-dir:
    description: 'Folder path to copy the assets'
    required: false
    default: './dist'
  token:
    description: 'GitHub Token for accessing private repos'
    required: false
    default: ${{ github.token }} # Fallback to the default runner token

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: "${{ github.action_path }}/uv.lock"

    - name: Run Ghuzzle
      shell: bash
      env:
        GZ_CONFIG: ${{ inputs.config }}
        GZ_BUILD_DIR:  ${{ inputs.build-dir }}
        GZ_TOKEN: ${{ inputs.token }}
        
        # Configuration for uv python version selection:
        # 'system' = prefer the runner's pre-installed python (if it matches pyproject.toml)
        # If system python is too old (e.g. <3.10), uv will auto-download a managed one.
        UV_PYTHON_PREFERENCE: system
                 
      run: |

        echo "Starting Ghuzzle"

        # --- Execution ---
        # 1. --project: Points to action_path (where pyproject.toml is)
        # 2. ghuzzle: Runs the script defined in [project.scripts]
        uv run \
          --project "${{ github.action_path }}" \
          ghuzzle